# Generated by Django 6.0.6 on 2026-09-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
    ]
